baby-0105/TTJ_LP

jun.html

initial commit

---

yama.html

commit again

---

package-lock.json
package.json
src/ejs/index.ejs
src/js/index.js
src/scss/object/project/_home.scss

index.ejs及びhome.scssの内容（案件・悩み）を変更しました。
ページに作成に必要だったため

悩みと案件部部の要素とcss深堀をしました

---

package-lock.json
src/ejs/index.ejs
src/js/index.js
src/scss/object/project/_home.scss
webpack.config.js

#what
アニメーション追加、index.ejs と home.scssの修正
#why
TTJ_LP作成のため

add animation, modifier index.ejs and home.scss

---

src/ejs/index.ejs
src/scss/layout/_top.scss
src/scss/object/project/_home.scss

Modified conflict error

---

package-lock.json
package.json
src/ejs/index.ejs
src/js/index.js
src/scss/object/project/_home.scss

#what
仕事までの流れ、案件部分の修正
円グラフの追加
#why
TTJ_LP作成のため

modified flowUpToWork and project, added pieList

---

src/js/index.js

コンパイル時のエラーを解決しました
全員のファイル修正状態を一定に保つために、こちらで修正

Resolved to compiled error

---

package-lock.json
package.json
src/ejs/index.ejs
src/ejs/template/_footer.ejs
src/js/index.js
src/scss/layout/_top.scss
src/scss/object/project/_home.scss

Add Modal to faqPC

---

package-lock.json
package.json
src/ejs/index.ejs
src/js/index.js
src/scss/object/project/_home.scss

#what
make slider
#why
TTJ_LPの内容修正のため

make slider

---

src/js/index.js
src/scss/app.scss
src/scss/foundation/_slick.scss

slick.scssファイルをコピーしてfoudation.scssフォルダに入れた
面倒なことをしないため

the copied slick.scss put in foundation.scss

---

src/ejs/index.ejs
src/js/index.js
src/scss/foundation/_var.scss
src/scss/layout/_top.scss
src/scss/object/component/_btn.scss
src/scss/object/project/_home.scss

slider, firstView, flowUpToWorkのレイアウトを諸々変更
見た目汚かったから

modified the layout of slider and btn of firstView, flowUpToWork

---

src/ejs/index.ejs
src/scss/foundation/_var.scss
src/scss/layout/_footer.scss
src/scss/layout/_top.scss
src/scss/object/component/_footer.scss
src/scss/object/project/_home.scss

Modified to variable

---

src/scss/foundation/_slick.scss
src/scss/foundation/_var.scss
src/scss/object/project/_home.scss

css,ejsの書き方を統一しました
リファクタリングのため

css,ejsの書き方を統一

---

src/scss/foundation/_slick.scss
src/scss/object/project/_home.scss

Modified conflicted code

---

public/about/index.html
public/index.html
src/ejs/index.ejs
src/scss/object/component/_btn.scss
src/scss/object/component/_footer.scss
src/scss/object/project/_home.scss

・faqのクリックイベント後の重なり修正
エラーであったため

Modified error code of enter block

---

src/ejs/index.ejs
src/scss/foundation/_var.scss
src/scss/object/project/_home.scss

modified the layout of project lang

---

src/scss/object/component/_btn.scss
src/scss/object/project/_home.scss

・lineのボタンのUIの不具合を修正
見た目の悪さを修正するため

Modified error of line btn

---

src/scss/object/component/_btn.scss

・案件を見るボタンの修正
#why
・spの時にボタンの見た目がおかしいため

Modified to show project btn

---

src/js/index.js

ファーストビューのフェードアウトするタイミングを少し遅らせた
ボタンが押しにくくなっていたから

modified firstview fadeout

---

public/about/index.html
public/index.html
src/ejs/index.ejs
src/scss/object/component/_btn.scss
src/scss/object/project/_home.scss

・実機での不具合を修正
→文字の折り返し、ボタンクリック後の挙動
・エラーをなくすため

Modified text white-space

---

src/ejs/index.ejs
src/js/index.js
src/scss/object/project/_home.scss

ファーストビューの背景画像の挙動修正と、円グラフをスマホレイアウトのときは縦に並べた
バグ修正とUI向上のため

modified the behavior of firstview and changed flex column pieList

---

public/about/index.html
public/index.html
src/js/index.js
src/scss/object/project/_home.scss

Modified graph
